# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7468f79dc7cf3b020bfe70a9c9f54c20a83fe1171ab1d1adfe03d8702e15f14cebf114c920f05e9a2434f1555f3bb01fc53ca85a777a5e15924a38515f0db366

test:
  secret_key_base: 569586f898cac38475928c546c00a9c39fcb4b23bce8b6db6d3ebb8c02befac56d164d5e9241e7cc804469f39c3e9fcbaf951f6dc7d6a1cb4d3f3a3e3055103c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
